#!/bin/bash

kill_list=
app_list=("firefox" "chrome" "teams" "skype" "subl" "keepass2")
for app in ${app_list[@]}
do
  kill_list+=($(ps -aux |grep $app | awk 'NR==1{print $2}'))
done

for app in ${kill_list[@]}
do
  kill $app
done
